### ISSUE TITLE
Cé nul

### ISSUE THREAD

**Issue by RGFRv2** [NogradThGin/script_collection#1]
Voilà.

**Comment by NogradThGin** [comment]
Merci de poster une erreur de log dmesg ainsi que le script en cause.
Aussi poster un inventaire detaillé de votre systeme et de ses differents details (/proc/cpuinfo entre autre).
Je reviendrais vers vous dans les plus bref delais.

**Comment by RGFRv2** [comment]
On a la même machine donc fait le toi même.
